### ISSUE TITLE
What if nodes has size, how to avoid overlap?

### ISSUE THREAD

**Issue by reactjser** [Platane/sugiyama-graph-drawing#1]
Is it possible to add some options, such as node size.

**Comment by Platane** [comment]
There is no notion of node size. The algorithm output position of node relative to each other.

In the demo page however, you can increase the size of the dot representing the node if that is what you are looking for.

**Comment by reactjser** [comment]
> There is no notion of node size. The algorithm output position of node relative to each other.
> 
> In the demo page however, you can increase the size of the dot representing the node if that is what you are looking for.

Thanks!
